### ISSUE TITLE
Multiple version conflict

### ISSUE THREAD

**Issue by pavan38kp** [substrate-developer-hub/substrate-node-template#329]
**Question**

Hello team
We are trying to run a chain that was bootstrapped from Substrate. But we're getting version conflict between dependencies.

So when we run `cargo build --release` we get the following outcome. 
```shell
error: failed to select a version for the requirement `sp-runtime = "^5.0.0"`
candidate versions found which didn't match: 6.0.0
location searched: Git repository https://github.com/paritytech/substrate?branch=master
required by package `fc-consensus v2.0.0-dev (https://github.com/paritytech/frontier.git?rev=8c772342787316d92cfb637a7028beb2de99b4dc#8c772342)`
    ... which satisfies git dependency `fc-consensus` of package `elysium v2.0.0 (/Users/pavankumar/Downloads/elysium-2/node)`

```
### cargo.toml 
```toml
[dependencies.sp-runtime]
branch = 'polkadot-v0.9.17'
git = 'https://github.com/paritytech/substrate?branch=polkadot-v0.9.17'
version = '5.0.0'
```
So here the logs say that the dependency `sp-runtime` v5.0.0 is specified in `cargo.toml` file, but the `fc-consensus` need v6.0.0. 

### cargo.toml 
```toml
[dependencies.sp-runtime]
branch = 'polkadot-v0.9.17'
git = 'https://github.com/paritytech/substrate?branch=polkadot-v0.9.17'
version = '6.0.0'
``` 
If we change the `sp-runtime` version to `6.0.0` in the `cargo.toml` file, then we get the following logs

``` shell
error: failed to select a version for the requirement `sp-runtime = "^6.0.0"`
candidate versions found which didn't match: 5.0.0
location searched: Git repository https://github.com/paritytech/substrate?branch=polkadot-v0.9.17?branch=polkadot-v0.9.17
required by package `elysium v2.0.0 (/Users/pavankumar/Downloads/elysium-2/node)`

```

Now it says dependency `elysium v2.0.0` requires `sp-runtime` version 5.0.0. 

Due to this version conflict, we're not able to run this node. Since cargo caches the dependencies that it installs, we're not able properly setup this node. 

This project uses substrate-node-template, and we did try to modify the `cargo.toml` with reference to the template repo. But it still doesn't work. 

Please let us know the fix for this issue, this has been a blocker for us for the past 4-to 5 days. Thank you.
